name: GCChangelog
version: 1.0
main: me.NinetyNine.gcchangelog.GCChangelog
author: NinetyNine
description: Shows changelog on GuildCraft.
commands:
  changelog:
    usage: /<command>
    description: Opens the book that shows the changes made.
    permission: changelog.open
  gcchangelog:
    usage: /<command>
    description: Adds a new change to the changelog book. 
    permission: changelog.admin
  gcchangelog add <type> <message>:
    usage: /<command>
    description: Adds a new change to the changelog book. 
    permission: changelog.admin
  gcchangelog undo:
    usage: /<command>
    description: Removed a change. The newest change is always 1 then second change 2 etc etc etc.
    permission: changelog.admin